### ISSUE TITLE
core.js.map not found

### ISSUE THREAD

**Issue by piotrpalek** [adzerk-oss/boot-cljs-example#11]
I've cloned the repo and run `boot dev`, when the page loads there is this error in the console (seems it can't find source maps): 
`GET http://localhost:3000/out/cljs/core.js.map 404 (Not Found)`

**Comment by myguidingstar** [comment]
Thanks for your feed back. Confirmed.
I've looked into the target/out/cljs and some .map files are missing
I haven't figured out why yet

**Comment by myguidingstar** [comment]
Fixed in https://github.com/Deraen/boot-cljs/commit/bc253c7afed494e81ca04477f54b0b5475f5d75d

**Comment by piotrpalek** [comment]
Thanks! :+1:
