### ISSUE TITLE
boot serve: no such task

### ISSUE THREAD

**Issue by gamecubate** [adzerk-oss/boot-cljs-example#22]
```boot serve -d target/ watch speak reload cljs-repl cljs -sO none``` doesn't work, returning ```clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException: No such task (serve)```.

**Comment by AdamFrey** [comment]
try `boot dev`. In `build.boot` the pipeline is consolidated into a task called `dev`. The Readme for this repo is a bit out of date.

**Comment by gamecubate** [comment]
Got it. Thanks!
